#rename labels

import os
import json

folder_path = "all/"

label_map = {
    
    "LANE_MARKING": ["INTERRUPTED_LANE_MARKING"],
    "EDGE_MARKING": ["UNINTERRUPTED_LANE_MARKING"],
    "FADED_EDGE_MARKING":["FADED_UNINTERRUPTED_LANE_MARKING"],
    "FADED_LANE_MARKING":["FADED_INTERRUPTED_LANE_MARKING", "FADED_LANE"],
    "15_74_SINGLE_CHEVRON":["15_74_SINGLE_CHEVRON(NORMAL)", "15_74_SINGLE_CHEVRON_NORMAL"],
    "17_09_U_TURN_AHEAD":["17_09_U-TURN_AHEAD"],
    "FADED_SIGN":["FADED_15_32_GAP_IN_MEDIAN", "FADED_SIGNAGES"],
    "15_78_OBJECT_HAZARD_LEFT":["15_78_OBJECT_HAZARD_(LEFT)", "15_78_OBJECT_HAZARD"],
    "DAMAGED_KERB":["KERB_DAMAGED"],
    "CHEVRON_MARKING":["DECELERATION_ZONE", "CHEVRON_MARKING_DIVERGING", "GORE_AREA_MARKING", "ACELERATION_ZONE"],
    "UNAUTHORIZED_MEDIAN_OPENING":["UNAUTHORIZED_MEDIAN_OPIENING"],
    "ARROW_MARKING":["BIFURCATION_ARROW_MARKING"],
    "FADED_ARROW_MARKING":["FADED_BIFURCATION_ARROW_MARKING"],
    "VEGETATION_KERB":["VEGETATED_KERB", "VEGETATION_KERB/VEGETATION_OBSTRUCTION AT KERB"],
    "ALLIGATOR_CRACKS":["ALLIGATOR_CRACK"],
    "FADED_CHEVRON_MARKING":["FADED_DECELERATION_ZONE", "FADED_GORE_AREA_MARKING", "FADED_ACELERATION_ZONE"],
    "VEGETATION_MBCB":["VEGETATION_OBSTRUCTION_AT_MBCB", "VEGETATION_OBSTRUCTION AT MBCB"],
    "16_01_STACK_TYPE_ADVANCE_DIRECTION_SIGN":["16.01 Stack Type Advance Direction Sign (Shoulder Mounted)", "16_01_STACK_TYPE_ ADVANCE_DIRECTION_SIGN"],
    "BLOCKED_DRAINAGE":["VEGETATED_DRAINAGE_CHANNEL", "VEGETATED _DRAINAGE_CHANNEL"],
    "GAP_IN_MEDIAN_VEGETATION":["MISSING_PLANTS"],
    "15_08_270_DEGREE_LOOP":["15.08 270 Degree Loop"],
    "15_80_TWO_WAY_OBJECT_HAZARD_MARKER":["15.80 Two Way Object Hazard Marker", "15_80_TWO_WAY_OBJECT HAZARD MARKER"],
    "FADED_ZEBRA_CROSSING":["FADED_PEDESTRAIN_CROSSING", "FADED_PEDESTRIAN_CROSSING"],
    "15_33_PEDESTRIAN_CROSSING":["15.33 Pedestrian Crossing", "15_33"],
    "14_52_PASS_EITHER_SIDE":["14.52 Pass Either Side"],
    "15_11_Y_INTERSECTION":["15.11 Y-Intersection"],
    "RAVELLING":["RAVELING"],
    "DAMAGED_SIGN":["DAMAGED_SIGNAGES"],
    "SLIPPAGE":["DELAMINATION"],
    "WATER_LOGGING":["WATER STAGNATION", "WATER_STAGNATION"],
    "VEGETATION_OBSTRUCTION_AT_POSTS":["VEGETATION_OBSTRUCTION_AT_SIGNAGE_POSTS"],
    "VEGETATION_GROWTH_ON_SHOULDERS":["VEGETATION GROWTH ON SHOULDERS"],
    "17_35_BUS_STOP":["17_35_Bus_Stop"],
    "MINOR_POTHOLE":["MINER_PORTHOLE"],
    "BLOCKED_KERB_DRAINAGE":["MEDIAN_VEGETATION_DRAINAGE"],
    "FADED_CONCRETE_BARRIER":["FADED CONCRETE CRASH BARRIER", "FADED_CONCRETE_CRASH_BARRIER", "FADED_CONCRETE_CRASS_BARRIER"],
    "VEGETATION_SIGN": ["VEGETATION_ROAD_SIGN"],
    "MISSING_STUDS": ["DAMAGED_ROAD_STUDS"],
    "15_22A_MERGING_TRAFFIC_AHEAD_FROM_RIGHT": ["15_22A _MERGING_TRAFFIC_AHEAD_FROM_RIGHT"],
    "DAMAGED_METAL_BEAM_CRASH_BARRIER": ["DAMAGED METAL BEAM CRASH BARRIER"],
    "UNAUTHORIZED_SIGN_BOARDS": ["UNAUTHORIZED SIGN BOARDS"],
    "14_42_RESTRICTION_END_SIGN" : ["14_42_RESTRICTION_END"],
    "15_22_MERGING_TRAFFIC_AHEAD_FROM_LEFT" : ["15_22 _MERGING_TRAFFIC_AHEAD_FROM_LEFT"],
    "14_40A_MAXIMUM_SPEED_LIMIT_VEHICLE_TYPE" : ["14_40A_MAXIMUM_SPEED_LIMIT"],
    "15_28_REDUCED_CARRIAGEWAY_LEFT_LANE_REDUCED" : ["15_28_REDUCED_CARRIAGEWAY_LEFT_LANES_REDUCED"],
    "16_10_GANTRY_MOUNTED_ADVANCE_DIRECTION_SIGN_AHEAD_OF_A_GRADE_SEPARATED_JUNCTI" : ["16_10_GANTRY_MOUNTED_ADVANCE_DIRECTION_SIGN_AHEAD_OF_GRADE_SEPARATED_JUNCTION"],
    "15_35_BUILT_UP_AREA" : ["15_35_BUILD_UP_AREA"],
    "16_04_FLAG_TYPE_DIRECTION_SIGN" : ["16_04_FLAG_TYPES_DIRECTIONAL_SIGN", "16_04_FLAG_TYPE_DIRECTIONAL_SIGN", "16.04 Flag Type Direction Sign"],
    "14_47_COMPULSORY_TURN_LEFT" :["14_47_COMPULSORY_LEFT"],
    "16_11_GANTRY_MOUNTED_ADVANCE_DIRECTION_AHEAD_OF_A_AT_GRADE_JUNCTION" : ["16_11_GANTRY_MOUNTED_ADVANCE_DIRECTION_SIGN_AHEAD_OF_AT_GRADE_JUNCTION", "16_11_GANTRY_MOUNTED_ADVANCE_DIRECTION_AHEAD_OF_A_AT_GRADE-JUNCTION"],
    "15_29_REDUCED_CARRIAGEWAY_RIGHT_LANE_REDUCED" : ["15_29_REDUCED_CARRIAGEWAY_RIGHT_LANES_REDUCED"],
    "15_32_GAP_IN_MEDIAN" : ["15_32_Gap_in_Median"],
    "17_06_FILLING_STATION" : ["17_06_FILLING_STATION_FUEL_PUMP"],
    "DAMAGED_CONCRETE_BARRIER" : ["DAMAGED_CONCRETE_CRASH_BARRIER"],
    
}

reverse_map = {}
for target, sources in label_map.items():
    for src in sources:
        reverse_map[src] = target

for filename in os.listdir(folder_path):
    if filename.endswith(".json"):
        filepath = os.path.join(folder_path, filename)
        with open(filepath, "r") as f:
            data = json.load(f)

        updated = False
        for shape in data.get("shapes", []):
            label = shape.get("label")
            if label in reverse_map:
                new_label = reverse_map[label]
                if new_label != label:
                    shape["label"] = new_label
                    updated = True
                    print(f"Updated label: {label} -> {new_label}")

        if updated:
            with open(filepath, "w") as f:
                json.dump(data, f, indent=4)
            print(f"Updated: {filename}")
